name: "Spell check"
on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-spell-check=${{github.ref}}-1
  cancel-in-progress: true

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install spell checker
        run: npm i -g yaspeller

      - name: Check spelling
        continue-on-error: true
        run: npx yaspeller en -e astro ./src/pages
